<a href="https://colab.research.google.com/github/thapaprabin/Machine_learning/blob/main/JOB_Recommend_system.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
'''import pandas as pd
df=pd.read_csv(r'/content/job_description.txt')
df.head()'''

"import pandas as pd\ndf=pd.read_csv(r'/content/job_description.txt')\ndf.head()"

**Read .txt file wrong **

In [ ]:
'''with open('/content/job_description.txt', 'r') as file:
    for i, line in enumerate(file):
        if i >= 10: # Display the first 10 lines to get an idea of the content
            break
        print(line.strip())'''

"with open('/content/job_description.txt', 'r') as file:\n    for i, line in enumerate(file):\n        if i >= 10: # Display the first 10 lines to get an idea of the content\n            break\n        print(line.strip())"

In [ ]:
from bs4 import BeautifulSoup

with open('/content/job_description.txt', 'r') as file:
    html_content = file.read()

soup = BeautifulSoup(html_content, 'html.parser')
text_content = soup.get_text(separator=' ', strip=True)

# Print the text content, replacing '. ' with '.\n' for better readability
print(text_content)

id|title|description
1|Senior Data Scientist|Role: Lead advanced analytics initiatives to uncover actionable insights from complex consumer datasets. Responsibilities: Architect end-to-end ML pipelines using Scikit-learn and Spark; perform rigorous A/B testing and hypothesis validation; mentor junior scientists on statistical best practices. Required Skills: Python (Pandas/NumPy), SQL, Bayesian Statistics, Feature Engineering, and experience with MLflow for experiment tracking.
2|Frontend Engineer|Role: Architect and implement high-performance, accessible user interfaces for flagship web products. Responsibilities: Translate complex Figma designs into modular React components; optimize Core Web Vitals and ensure cross-browser consistency; collaborate with Backend teams on GraphQL schema design. Required Skills: React.js, TypeScript, Next.js, CSS-in-JS (Styled Components), Tailwind CSS, and automated testing with Cypress.
3|Technical Project Manager|Role: Direct the execution of cross-functional software engineering projects from discovery to deployment. Responsibilities: Facilitate Agile ceremonies (Scrum/Kanban); manage project scope, velocity, and resource allocation in Jira; act as the primary liaison between Engineering and Executive stakeholders. Required Skills: PMP or CSM Certification, Jira/Confluence, Risk Mitigation, SDLC expertise, and Strong Communication.
4|Cloud DevOps Engineer|Role: Design and maintain resilient, automated cloud infrastructure to support global-scale applications. Responsibilities: Implement Infrastructure as Code (IaC) using Terraform; manage container orchestration via Kubernetes (EKS/GKE); lead disaster recovery planning and security patching. Required Skills: AWS/Azure, Docker, Kubernetes, CI/CD (GitHub Actions/Jenkins), Bash, and Prometheus monitoring.
5|Cybersecurity Architect|Role: Define and enforce the security posture of the enterprise network and cloud environments. Responsibilities: Conduct comprehensive threat modeling and penetration testing; manage Zero Trust architecture and IAM policies; lead the Security Operations Center (SOC) during active incidents. Required Skills: CISSP, Kali Linux, Network Security, SIEM (Splunk), IAM, and Cryptographic protocols.
6|Backend Systems Developer|Role: Build and scale high-concurrency server-side applications and distributed systems. Responsibilities: Design RESTful and gRPC APIs; optimize database query performance and indexing strategies; manage message queuing for asynchronous processing. Required Skills: Node.js, Go (Golang), PostgreSQL, Redis, RabbitMQ/Kafka, and Microservices architecture.
7|UX/UI Product Designer|Role: Design user-centric digital products that balance aesthetic appeal with functional simplicity. Responsibilities: Execute full-cycle design from wireframing to high-fidelity prototyping; conduct usability testing and accessibility (WCAG) audits; maintain a robust design system. Required Skills: Figma, Adobe Creative Cloud, User Research, Interaction Design, and Visual Storytelling.
8|Full Stack Software Engineer|Role: Develop and own features across the entire application stack, from UI to database. Responsibilities: Build responsive frontends and secure backends; perform peer code reviews and contribute to system architecture discussions; debug complex production issues. Required Skills: JavaScript (ES6+), Python/Django, React, PostgreSQL, Git, and REST API design.
9|Machine Learning Engineer|Role: Bridge the gap between data science research and production-level software engineering. Responsibilities: Deploy high-performance models using TorchServe or TensorFlow Serving; implement MLOps patterns for automated retraining; optimize model quantization for edge devices. Required Skills: PyTorch, TensorFlow, MLOps, Computer Vision, NLP, and Deep Learning optimization.
10|Data Engineer|Role: Design and build the foundational data infrastructure for analytics and business intelligence. Responsibilities: Construct robust ETL/ELT pipelines to move data into Snowflake or BigQuery; ensure data quality, masking, and compliance with GDPR/CCPA. Required Skills: Apache Spark, Airflow, SQL, Python, dbt, Snowflake, and Data Warehousing concepts.
11|QA Automation Engineer|Role: Lead the quality assurance strategy through automated testing frameworks. Responsibilities: Develop and maintain end-to-end test suites; integrate automated checks into the CI/CD pipeline; perform exploratory manual testing for new features. Required Skills: Selenium, Playwright, Python, Pytest, Load Testing (Locust), and Jira.
12|Mobile App Developer|Role: Engineer high-performance mobile experiences for iOS and Android. Responsibilities: Build cross-platform applications with a focus on smooth animations and offline-first capabilities; manage App Store and Play Store release cycles. Required Skills: React Native, Flutter, Swift, Kotlin, Firebase, and Mobile Design Patterns.
13|Site Reliability Engineer (SRE)|Role: Ensure the reliability, scalability, and efficiency of production services. Responsibilities: Apply software engineering principles to operations; manage "error budgets" and toil reduction; lead "Post-Mortem" analysis for outages. Required Skills: Python/Go, Kubernetes, Terraform, Grafana, Linux Internals, and Incident Management.
14|AI Product Manager|Role: Define the vision and roadmap for AI-powered features and automation products. Responsibilities: Identify high-impact AI use cases; manage the trade-offs between model accuracy and latency; translate business requirements into technical specs for ML teams. Required Skills: Product Lifecycle Management, Market Analysis, AI Ethics, Agile, and Data-driven Decision Making.
15|Blockchain Developer|Role: Develop decentralized applications (dApps) and secure smart contracts. Responsibilities: Audit code for reentrancy vulnerabilities; optimize gas consumption on EVM-compatible chains; implement Layer 2 scaling solutions. Required Skills: Solidity, Rust, Web3.js, Ethers.js, Cryptography, and Consensus Algorithms.
16|Solutions Architect|Role: Design comprehensive technical solutions that align with business goals and IT infrastructure. Responsibilities: Lead technical discovery sessions with clients; create architectural diagrams and proofs-of-concept; evaluate third-party vendors and integration strategies. Required Skills: Enterprise Architecture, Cloud Strategy, Pre-sales, and Stakeholder Management.
17|Data Analyst|Role: Transform raw data into meaningful visualizations and reports for executive decision-making. Responsibilities: Clean and validate data from multiple sources; create interactive dashboards in Tableau or PowerBI; perform cohort analysis and trend forecasting. Required Skills: SQL, Tableau/PowerBI, Excel (Advanced), Statistics, and Data Storytelling.
18|Systems Administrator|Role: Manage and support internal IT infrastructure, including servers, networks, and workstations. Responsibilities: Administer Active Directory and Microsoft 365; manage local network security and VPNs; provide Tier 3 technical support. Required Skills: Windows Server, Linux (Ubuntu/CentOS), Active Directory, Networking (TCP/IP), and Hardware troubleshooting.
19|Embedded Systems Engineer|Role: Design and develop firmware for hardware devices and IoT sensors. Responsibilities: Write low-level code for microcontrollers (ARM/ESP32); optimize power consumption and memory usage; interface with sensors via I2C/SPI. Required Skills: C, C++, RTOS, Circuit Design, Debugging (JTAG/GDB), and Firmware architecture.
20|Digital Marketing Specialist|Role: Drive user acquisition and brand awareness through data-driven digital channels. Responsibilities: Manage PPC campaigns on Google/Meta; optimize conversion rate (CRO) for landing pages; track ROI using Google Analytics 4. Required Skills: Google Ads, SEO, SEM, Content Strategy, and Performance Marketing.
21|Game Developer|Role: Create immersive gameplay experiences and interactive 3D environments. Responsibilities: Implement game mechanics and AI behavior; optimize rendering performance for various platforms; collaborate with artists on asset integration. Required Skills: C#, C++, Unity, Unreal Engine, 3D Mathematics, and Shader programming.
22|Technical Writer|Role: Produce clear and concise documentation for complex software and APIs. Responsibilities: Create developer portals and API references; write "Getting Started" guides and troubleshooting manuals; work with engineers to document system architecture. Required Skills: Markdown, DITA, API Documentation (Swagger/OpenAPI), Git, and Instructional Design.
23|Sales Engineer|Role: Support the sales team by providing deep technical expertise during product demonstrations. Responsibilities: Build custom technical demos for prospective clients; answer security and architecture questionnaires; act as the technical voice of the customer to the Product team. Required Skills: Presentation Skills, Pre-sales, API integrations, and Technical Problem Solving.
24|Database Administrator (DBA)|Role: Ensure the performance, integrity, and security of production databases. Responsibilities: Manage database migrations and backups; perform query tuning and index optimization; ensure high availability and failover clusters. Required Skills: MySQL, PostgreSQL, Oracle, NoSQL (MongoDB), Backup & Recovery, and Database Security.
25|SEO Specialist|Role: Improve organic search visibility and drive high-quality traffic to web properties. Responsibilities: Conduct keyword research and competitive analysis; perform technical SEO audits (schema, crawling, indexing); manage backlink strategies. Required Skills: Google Search Console, Ahrefs, SEMrush, Technical SEO, and Content Optimization.
26|Customer Success Engineer|Role: Assist enterprise clients in integrating and maximizing value from technical products. Responsibilities: Troubleshoot complex integration issues; lead technical onboarding sessions; identify expansion opportunities based on product usage. Required Skills: Troubleshooting, API Support, Customer Relations, and Product Training.
27|Hardware Engineer|Role: Design and test physical components and circuit boards for consumer electronics. Responsibilities: Develop PCB layouts and schematics; conduct signal integrity analysis and thermal testing; manage relationships with manufacturing vendors. Required Skills: PCB Design (Altium/Eagle), FPGA, VHDL, Hardware Debugging, and Prototyping.
28|Bioinformatics Scientist|Role: Apply computational methods to analyze biological and genomic data for drug discovery. Responsibilities: Build pipelines for Next-Generation Sequencing (NGS); perform statistical analysis on clinical trial data; visualize protein structures. Required Skills: Python/R, Biostatistics, Genomic Data Analysis, SQL, and Molecular Biology knowledge.
29|Financial Quantitative Analyst|Role: Develop mathematical models for pricing, risk management, and algorithmic trading. Responsibilities: Implement Monte Carlo simulations and stochastic calculus models; backtest trading strategies using historical data; monitor portfolio risk metrics. Required Skills: Python/C++, Quantitative Finance, Stochastic Calculus, Statistics, and Financial Modeling.
30|HR Tech Specialist|Role: Manage and optimize Human Resources Information Systems (HRIS) and recruitment technology. Responsibilities: Integrate ATS and payroll systems; analyze employee engagement data; manage system permissions and data privacy. Required Skills: Workday/BambooHR, Data Privacy (GDPR), HR Analytics, and Project Management.
31|Network Engineer|Role: Design, implement, and support corporate and data center networks. Responsibilities: Configure routers, switches, and firewalls; monitor network performance and latency; manage SD-WAN and MPLS circuits. Required Skills: Cisco/Juniper, Routing Protocols (BGP/OSPF), Firewalls, VPN, and Network Security.
32|Product Owner|Role: Maximize the value of the product by managing the engineering team’s backlog. Responsibilities: Define and prioritize "User Stories"; accept or reject work based on "Definition of Done"; represent the customer's voice in planning. Required Skills: Agile, Product Management, Backlog Grooming, and Stakeholder Communication.
33|Scrum Master|Role: Serve the team by removing impediments and facilitating a healthy Agile environment. Responsibilities: Facilitate Sprint Planning, Retrospectives, and Daily Standups; shield the team from outside interruptions; coach the organization on Agile values. Required Skills: Scrum, Kanban, Servant Leadership, Conflict Resolution, and Process Improvement.
34|Technical Support Engineer|Role: Resolve high-level technical issues for enterprise software customers. Responsibilities: Reproduce bugs in local environments; escalate critical issues to Engineering; maintain a knowledge base of known solutions. Required Skills: Linux/Unix commands, SQL queries, Troubleshooting, and Technical Communication.
35|Cloud Architect|Role: Define the high-level cloud strategy and architectural standards for the organization. Responsibilities: Evaluate multi-cloud versus hybrid cloud approaches; design cost-optimization strategies; ensure architectural compliance with security frameworks. Required Skills: AWS/Azure/GCP Solutions Architect Professional, Cloud Governance, and Enterprise Design.
36|Business Systems Analyst|Role: Analyze business processes and translate them into functional requirements for IT systems. Responsibilities: Document "As-Is" and "To-Be" process flows; manage User Acceptance Testing (UAT); ensure systems meet operational needs. Required Skills: Gap Analysis, Requirements Gathering, Visio, and SQL.
37|E-commerce Manager|Role: Oversee the technical and commercial operations of online retail platforms. Responsibilities: Manage product catalogs and conversion funnels; optimize site search and checkout processes; coordinate with Logistics and Marketing teams. Required Skills: Shopify/Magento, Analytics, Inventory Management, and Customer Journey Mapping.
38|Robotics Engineer|Role: Design and program robotic systems for manufacturing and automation. Responsibilities: Implement path planning and control algorithms; integrate computer vision for object recognition; perform hardware-software integration testing. Required Skills: ROS (Robot Operating System), C++, Python, Control Theory, and Mechatronics.
39|Computer Vision Engineer|Role: Develop algorithms that allow machines to interpret and understand visual data. Responsibilities: Implement object detection, image segmentation, and facial recognition models; optimize models for real-time mobile inference. Required Skills: OpenCV, PyTorch, C++, Image Processing, and Deep Learning.
40|NLP Engineer|Role: Build systems that understand, interpret, and generate human language. Responsibilities: Develop Large Language Model (LLM) applications; implement sentiment analysis and named entity recognition (NER); fine-tune models on domain-specific text. Required Skills: HuggingFace, Transformers, Python, Linguistics, and Vector Databases (Pinecone/Milvus).
41|Big Data Architect|Role: Design large-scale distributed systems for processing massive volumes of data. Responsibilities: Evaluate technologies like Hadoop, Spark, and NoSQL; design data lake and delta lake architectures; ensure system scalability and fault tolerance. Required Skills: Distributed Systems, Hadoop, Spark, NoSQL, and High-Volume Data Processing.
42|IT Auditor|Role: Evaluate the effectiveness of the organization’s IT controls and security measures. Responsibilities: Perform internal audits against SOC2 or ISO 27001 standards; identify control gaps and recommend remediations; report findings to the board. Required Skills: CISA, IT Governance, Risk Management, and Compliance knowledge.
43|Video Game Producer|Role: Manage the production schedule, budget, and team coordination for game development. Responsibilities: Ensure milestones are met on time; manage external outsourcing partners; facilitate communication between art, code, and design departments. Required Skills: Project Management, Budgeting, Game Development Pipeline, and Leadership.
44|Social Media Manager|Role: Build and engage the online community across various social platforms. Responsibilities: Create content calendars and visual assets; monitor brand sentiment and engagement metrics; manage influencer partnerships. Required Skills: Social Media Analytics, Content Creation, Copywriting, and Community Management.
45|ERP Consultant|Role: Implement and customize Enterprise Resource Planning systems like SAP or Oracle. Responsibilities: Configure system modules to meet business requirements; lead data migration efforts from legacy systems; provide end-user training. Required Skills: SAP/Oracle ERP, Business Process Mapping, SQL, and Change Management.
46|Legal Tech Specialist|Role: Bridge the gap between legal departments and information technology. Responsibilities: Manage e-discovery platforms and contract management systems (CLM); ensure digital compliance with legal holds; automate document generation. Required Skills: Legal Tech software, Data Privacy, Process Automation, and Document Management.
47|Interaction Designer|Role: Focus on how users interact with digital products through movement and feedback. Responsibilities: Create motion graphics and micro-interactions; design logical task flows and navigation structures; prototype interactive experiences. Required Skills: Principle, After Effects, Figma, and User-Centered Design.
48|Information Architect|Role: Organize and structure content to help users find information easily. Responsibilities: Create sitemaps and taxonomy structures; conduct card sorting exercises; design navigation systems for large-scale enterprise websites. Required Skills: Content Strategy, Taxonomy, Wireframing, and User Research.
49|Content Strategist|Role: Plan and govern the creation and distribution of useful, usable content. Responsibilities: Develop brand voice guidelines; conduct content audits and gap analysis; align content goals with business objectives. Required Skills: Copywriting, Content Auditing, SEO, and Editorial Planning.
50|Growth Hacker|Role: Use data-driven, creative strategies to achieve rapid user base growth. Responsibilities: Conduct viral marketing experiments; optimize referral loops and onboarding flows; analyze funnel drop-offs using behavioral data. Required Skills: A/B Testing, Analytics, Product-led Growth (PLG), and Marketing Automation.

In [10]:
import io
import pandas as pd

# Treat the text_content as a file-like object
data_io = io.StringIO(text_content)

# Read the data using pandas, specifying the pipe separator
df = pd.read_csv(data_io, sep='|', index_col='id')

# Extract the 'title' and 'description' columns as Series
title = df['title']
description= df['description']

print("Title Series Head:")
display(title.head())

print("\nDescription Series Head:")
display(description.head())

Title Series Head:

id
1        Senior Data Scientist
2            Frontend Engineer
3    Technical Project Manager
4        Cloud DevOps Engineer
5      Cybersecurity Architect
Name: title, dtype: object

Description Series Head:

id
1    Role: Lead advanced analytics initiatives to u...
2    Role: Architect and implement high-performance...
3    Role: Direct the execution of cross-functional...
4    Role: Design and maintain resilient, automated...
5    Role: Define and enforce the security posture ...
Name: description, dtype: object

In [5]:
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import PorterStemmer
import nltk
nltk.download('punkt_tab')
nltk.download('stopwords')

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

True

In [ ]:
def text_clean(text):
  #text=text.lower()
  #converting to tokens
  tokens=word_tokenize(text)
  #stopwords removal
  stop_words=set(stopwords.words('english'))
  filterd_tokens=[word for word in tokens if word not in stop_words]
  #now that we have filtered tokens without stopwords
  stemmer=PorterStemmer()
  stemmed_tokens=[stemmer.stem(word) for word in filterd_tokens]
  cleaned_document=" ".join(stemmed_tokens)
  return cleaned_document

1.function text_cleaned built to tokenize,stemming and stopwrds.

2.Loaded job description.txt with the help of beaitiful soup.

3.Divided the txt file into title and description series
bold text

In [14]:
#LETS CONVERT THE JOB DESCRIPTION TO NUMBERS USING TFIDF VECTORIZER
from sklearn.feature_extraction.text import TfidfVectorizer

cleaned_description=description.apply(text_clean)
#description series ma text_clean function apply gareko to clean
tfidf=TfidfVectorizer()
#class creation of tfidf vectorizer
tfidf_matrix=tfidf.fit_transform(cleaned_description)
#lets see the matrix
print(tfidf_matrix.shape)

(50, 763)

In [12]:
def process_text_to_vector(raw_text, fitted_tfidf):


    cleaned = text_clean(raw_text)


    vector = fitted_tfidf.transform([cleaned])

    return vector

Numerical Vector (as sparse matrix):
<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 4 stored elements and shape (1, 763)>
  Coords	Values
  (0, 171)	0.36093130195197276
  (0, 541)	0.4267405771533032
  (0, 610)	0.6879614328590318
  (0, 660)	0.46295803479437253

In [16]:
resume1="A motivated and detail-oriented Machine Learning Engineer with a strong foundation in Python, machine learning algorithms, data preprocessing, and model deployment. Experienced in developing predictive models, feature engineering, and evaluating model performance using libraries such as Scikit-learn, TensorFlow, and PyTorch. Passionate about solving real-world problems through artificial intelligence and continuously improving technical skills while collaborating effectively within cross-functional teams."
#resume2="A data-driven and analytical Data Scientist with expertise in statistical analysis, data visualization, and extracting actionable insights from complex datasets. Proficient in Python, SQL, Pandas, NumPy, and visualization tools such as Matplotlib and Power BI. Skilled in data cleaning, exploratory data analysis, predictive modeling, and communicating findings to support data-informed decision-making in business and research environments."

In [17]:
# 1. Clean the resume text
cleaned_resume = text_clean(resume1)

# 2. Convert to numerical form using the fitted tfidf model
# This uses the process_text_to_vector function defined earlier
resume_vector = process_text_to_vector(resume1, tfidf)

# 3. Print results
print("Cleaned Text Sample:")
print(cleaned_resume[:100], "...")

print("\nNumerical Vector (Sparse Matrix Representation):")
print(resume_vector)

Cleaned Text Sample:
a motiv detail-ori machin learn engin strong foundat python , machin learn algorithm , data preproce ...

Numerical Vector (Sparse Matrix Representation):
<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 30 stored elements and shape (1, 763)>
  Coords	Values
  (0, 23)	0.1334208170430668
  (0, 119)	0.15393460948010335
  (0, 160)	0.14238184069253798
  (0, 171)	0.08930262208572193
  (0, 186)	0.15393460948010335
  (0, 189)	0.0982636457351931
  (0, 213)	0.15393460948010335
  (0, 223)	0.21117067034122336
  (0, 237)	0.1334208170430668
  (0, 251)	0.1334208170430668
  (0, 268)	0.1702173225649931
  (0, 273)	0.1702173225649931
  (0, 328)	0.15393460948010335
  (0, 341)	0.1702173225649931
  (0, 379)	0.4271455220776139
  (0, 396)	0.3404346451299862
  (0, 436)	0.35972618218489844
  (0, 495)	0.08427630661549051
  (0, 524)	0.1702173225649931
  (0, 541)	0.10558533517061168
  (0, 542)	0.15393460948010335
  (0, 555)	0.1702173225649931
  (0, 611)	0.1702173225649931
  (0, 641)	0.04015811165814563
  (0, 651)	0.1702173225649931
  (0, 672)	0.1702173225649931
  (0, 686)	0.11454635882008286
  (0, 688)	0.10981641452275846
  (0, 690)	0.1702173225649931
  (0, 729)	0.10981641452275846

In [18]:
from sklearn.metrics.pairwise import cosine_similarity

# Calculate similarity between the resume vector and all job description vectors
# resume_vector is (1, 763) and tfidf_matrix is (50, 763)
similarity_scores = cosine_similarity(resume_vector, tfidf_matrix)

# Add the scores to our original dataframe for easy viewing
df['similarity_score'] = similarity_scores.flatten()

# Sort by highest similarity and display the top 5 matches
top_matches = df[['title', 'similarity_score']].sort_values(by='similarity_score', ascending=False)

print("Top 5 Job Matches for Resume 1:")
display(top_matches.head(5))

Top 5 Job Matches for Resume 1:

                             title  similarity_score
id
39        Computer Vision Engineer          0.352917
9        Machine Learning Engineer          0.322039
29  Financial Quantitative Analyst          0.189615
1            Senior Data Scientist          0.157539
23                  Sales Engineer          0.146168